export const userConstants = {
  FETCH_USER_REQUEST: 'FETCH_USER_REQUEST',
  FETCH_USER_SUCCESS: 'FETCH_USER_SUCCESS',
  FETCH_USER_FAILURE: 'FETCH_USER_FAILURE',

  CREATE_USER_REQUEST: 'CREATE_USER_REQUEST',
  CREATE_USER_SUCCESS: 'CREATE_USER_SUCCESS',
  CREATE_USER_FAILURE: 'CREATE_USER_FAILURE',

  UPDATE_USER: 'UPDATE_USER',

  UPDATE_USER_REQUEST: 'UPDATE_USER_REQUEST',
  UPDATE_USER_SUCCESS: 'UPDATE_USER_SUCCESS',
  UPDATE_USER_FAILURE: 'UPDATE_USER_FAILURE',

  UPDATE_USER_LOCATION: 'UPDATE_USER_LOCATION_SUCCESS',

  SUBSCRIBE_USER_REQUEST: 'SUBSCRIBE_USER_REQUEST',
  SUBSCRIBE_USER_SUCCESS: 'SUBSCRIBE_USER_SUCCESS',
  SUBSCRIBE_USER_FAILURE: 'SUBSCRIBE_USER_FAILURE',

  UNSUBSCRIBE_USER_REQUEST: 'UNSUBSCRIBE_USER_REQUEST',
  UNSUBSCRIBE_USER_SUCCESS: 'UNSUBSCRIBE_USER_SUCCESS',
  UNSUBSCRIBE_USER_FAILURE: 'UNSUBSCRIBE_USER_FAILURE',

  CHECK_VERIFICATION_CODE_REQUEST: 'CHECK_VERIFICATION_CODE_REQUEST',
  CHECK_VERIFICATION_CODE_SUCCESS: 'CHECK_VERIFICATION_CODE_SUCCESS',
  CHECK_VERIFICATION_CODE_FAILURE: 'CHECK_VERIFICATION_CODE_FAILURE',
};
