export const authConstants = {
  CREATE_AUTH_REQUEST: 'CREATE_AUTH_REQUEST',
  CREATE_AUTH_SUCCESS: 'CREATE_AUTH_SUCCESS',
  CREATE_AUTH_FAILURE: 'CREATE_AUTH_FAILURE',

  SIGN_UP_REQUEST: 'SIGN_UP_REQUEST',
  SIGN_UP_SUCCESS: 'SIGN_UP_SUCCESS',
  SIGN_UP_FAILURE: 'SIGN_UP_FAILURE',


  RESET_PASSWORD_REQUEST: 'RESET_PASSWORD_REQUEST',
  RESET_PASSWORD_SUCCESS: 'RESET_PASSWORD_SUCCESS',
  RESET_PASSWORD_FAILURE: 'RESET_PASSWORD_FAILURE',

  SET_TOKEN_REQUEST: 'SET_TOKEN_REQUEST',
  SET_TOKEN_SUCCESS: 'SET_TOKEN_SUCCESS',

  REMOVE_TOKEN_SUCCESS: 'REMOVE_TOKEN_SUCCESS'
};
