export const en = {
  singIn: 'Login',
  signUp: 'Register',
  publish: 'Publish',
  forgotPassword: 'Forgot password?',
  continue: 'Continue',
  newActivities: 'New activities',
  newPost: 'New post',
  last_name: 'Last Name',
  privacyPolicy: 'Privacy Policy',
  first_name: 'First Name',
  title: 'Title',
  beforeRegistration: 'before registration',
  pleaseReadThe: 'Please read the ',
  description: 'Description',
  categories: 'Categories',
  updateSuccessfully: 'Update successfully!',
  mustHaveAtLeastOneCategory: 'Must have at least one category!',
  add: 'Add',
  information: 'Information',
  createSuccessfully: 'Create successfully!',
  aboutMe: 'About me',
  addSocialNetworks: 'Add social networks where you can be contacted',
  noResults: 'Sorry, no results were found for your search. Please try again later!',
  phone: 'Phone',
  noResultsFriends: 'Posts of friends you follow',
  noResultsFollowings: 'Posts you follow',
  noResultsActual: 'Actual publications of all users',

  noResultsActivities: 'Your publications',
  noResultsFollowingsTitle: 'The people you follow',
  noResultsFollowingsSubtitle: 'When you start following people they will show up here',
  noResultsFollowersTitle: 'Followers',
  noResultsFollowersSubtitle: 'People who are following you will be displayed here',

  find: 'Find',
  delete: 'Delete',
  noMembers: 'No members yet, be the first',
  edit: 'Edit',
  save: 'Save',
  cancel: 'Cancel',
  search: 'Search',
  clear: 'Clear',
  location: 'Location',
  apply: 'Apply',
  inRadius: 'With in a radius',
  myLocation: 'My location',
  enterCityName: 'Enter city name',
  settings: 'Settings',
  ukraine: 'Ukraine',
  change_password: 'Change password',
  logout: 'Logout',
  actual: 'Actual',
  filters: 'Filters',
  friends: 'Friends',
  oldPassword: 'Old password',
  thisLoginAlreadyTaken: 'This login is already taken!',
  language: 'Language',
  my: 'My',
  password: 'Password',
  tagline: 'We do not build boundaries between people, we bring them together.',
  enter_your_email:
    'Enter your email to which you should receive a letter with a confirmation code',
  password_mismatch: 'Password mismatch!',
  repeat_password: 'Repeat password',
  login: 'Login',
  minimumOneSocialNetwork: 'Add at least one social network!',
  fieldIsRequired: 'The field is required!',
  socialNetwork: 'My social network',
  fields_to_complete_registration:
    'Fill in all fields to continue registration',
  confirmation_code: 'Confirmation code',
  enter_the_code_that_came_to_your_mail:
    'Enter the code that came to your mail',
  resend_code: 'Resend code',
  resend_code_via: 'Resend code via',
  seconds: 'seconds',
  minimum_six_characters: 'Minimum 6 characters!',
  who_would_you_like: 'Who would you like to perform the action with?',
  a_man: 'A man',
  a_women: 'A woman',
  by_the_company: 'By the company',
  all_the_same: 'All the same',
  select_categories: 'Select categories',
  category_search: 'Category search',
  add_categories_maximum: 'Add categories, maximum 3',
  edit_profile: 'Edit profile',
  unfollow: 'Unfollow',
  following: 'Following',
  follow: 'Follow',
  followers: 'Followers',
  followings: 'Followings',
  publications: 'Publications',
  age: 'Age',
  unmarried: 'Unmarried',
  dating: 'Dating',
};
