export const ru = {
  singIn: 'Вход',
  signUp: 'Регистрация',
  publish: 'Публиковать',
  forgotPassword: 'Забыли пароль?',
  continue: 'Продолжить',
  password: 'Пароль',
  edit: 'Редактировать',
  actual: 'Актуальные',
  last_name: 'Фамилия',
  first_name: 'Имя',
  newPost: 'Новавя публикация',
  privacyPolicy: 'Политика Конфиденциальности',
  pleaseReadThe: 'Пожалуйста, прочтите ',
  beforeRegistration: 'перед регистрацией',
  my: 'Мои',
  friends: 'Друзья',
  information: 'Информация',
  oldPassword: 'Старый пароль',
  createSuccessfully: 'Успешно создано!',
  updateSuccessfully: 'Обновление прошло успешно!',
  noMembers: 'Пока нет участников, стань первым',
  noResults: 'К сожалению, ничего по запросу не найдено. Попробуйте еще раз чуть позже!',
  mustHaveAtLeastOneCategory: 'Должна быть хотя бы одна категория!',
  search: 'Поиск',
  minimumOneSocialNetwork: 'Добавьте хотя бы одну соцсеть!',
  thisLoginAlreadyTaken: 'Этот логин уже занят!',
  filters: 'Фильтры',
  fieldIsRequired: 'Поле обязательное!',
  settings: 'Настройки',
  change_password: 'Изменить пароль',
  logout: 'Выйти',
  language: 'Язык',
  find: 'Найти',
  ukraine: 'Украина',
  cancel: 'Отменить',
  clear: 'Очистить',
  delete: 'Удалить',
  location: 'Местоположение',
  apply: 'Применить',
  inRadius: 'В радисе',
  myLocation: 'Мое местоположение',
  enterCityName: 'Введите название города',
  tagline: 'Мы не строим границ между людьми, мы объединяем их.',
  enter_your_email:
    'Введите вашу электронную почту на которое должно прийти письмо с кодом подтверждения',
  password_mismatch: 'Пароли не совпадают!',
  repeat_password: 'Повторите пароль',
  login: 'Логин',
  fields_to_complete_registration:
    'Заполните все поля чтобы продолжить регистрацию',
  confirmation_code: 'Код подтверждения',
  enter_the_code_that_came_to_your_mail:
    'Введите код, который пришел вам на почту',
  resend_code: 'Отправить код еще раз',
  resend_code_via: 'Повторно отправить код через',
  seconds: 'секунды',
  aboutMe: 'Обо мне',
  addSocialNetworks: 'Добавьте социальные сети в которых  с вами можно связаться',
  minimum_six_characters: 'Минимум 6 символов!',
  newActivities: 'Новая активность',
  title: 'Заголовок',
  socialNetwork: 'Мои соцсети',
  description: 'Описание',
  categories: 'Категории',
  add: 'Добавить',
  who_would_you_like: 'С кем бы вы хотели выполнить действие?',
  a_man: 'Мужчиной',
  a_women: 'Женщиной',
  by_the_company: 'Компанией',
  all_the_same: 'Все ровно',
  select_categories: 'Выберете категории',
  unfollow: 'Отписаться',
  follow: 'Подписаться',
  category_search: 'Поиск категории',
  add_categories_maximum: 'Добавьте категории, максимально 3',
  edit_profile: 'Редактировать профиль',
  following: 'Вы подписаны',
  followers: 'Подписчики',
  followings: 'Подписики',
  publications: 'Публикации',
  save: 'Сохранить',
  age: 'Возраст',
};
