export const ua = {
  singIn: 'Вхід',
  signUp: 'Реєстрація',
  publish: 'Опублікувати',
  forgotPassword: 'Забули пароль?',
  continue: 'Продовжити',
  password: 'Пароль',
  tagline: "Ми не будуємо кордонів між людьми, ми об'єднуємо їх.",
  edit: 'Редагувати',
  actual: 'Актуальні',
  last_name: 'Фамілія',
  information: 'Інформація',
  aboutMe: 'Про мене',
  createSuccessfully: 'Успішно створено!',
  updateSuccessfully: 'Оновлення пройшло успішно!',
  mustHaveAtLeastOneCategory: 'Має бути хоча б одна категорія!',
  first_name: 'Ім`я',
  noMembers: 'Поки немає учасників, стань першим',
  filters: 'Фільтри',
  addSocialNetworks: `Додайте соціальні мережі, в яких з вами можна зв'язатися`,
  noResults: 'На жаль, нічого за запитом не знайдено. Cпробуйте ще раз трохи пізніше!',
  noResultsFriends: 'Дописи друзів за якими ви стежите',
  noResultsFollowings: 'Дописи за якими ви стежите',
  noResultsActual: 'Актуальні дописи усіх користувачів',

  noResultsActivities: 'Ваші публікації',
  noResultsFollowingsTitle: 'Люди за якими ви стежите',
  noResultsFollowingsSubtitle: 'Коли ви почнете стежите за людьми , вони відображатимуться тут',
  noResultsFollowersTitle: 'Читачі',
  noResultsFollowersSubtitle: 'Тут відображатимуться люди , які стежать за вами',

  search: 'Пошук',
  settings: 'Налаштування',
  change_password: 'Змінити пароль',
  logout: 'Вийти',
  language: 'Мова',
  my: 'Мої',
  find: 'Знайти',
  delete: 'Видалити',
  cancel: 'Відмінити',
  clear: 'Очистити',
  location: 'Розташування',
  apply: 'Застосувати',
  inRadius: 'В радіусі',
  myLocation: 'Моє розташування',
  enterCityName: 'Введіть названу міста',
  ukraine: 'Україна',
  newPost: 'Нова публікація',
  privacyPolicy: 'Політика Конфіденційності',
  pleaseReadThe: 'Будь ласка, прочитайте ',
  beforeRegistration: 'перед реєстрацією',
  friends: 'Друзі',
  oldPassword: 'Старий пароль',
  enter_your_email:
    'Введіть вашу електронну пошту, на який має прийти лист із кодом підтвердження',
  password_mismatch: 'Паролі не співпадають!',
  repeat_password: 'Повторіть пароль',
  login: 'Логін',
  minimumOneSocialNetwork: 'Додайте хоча б одну соцмережу',
  socialNetwork: 'Мої соцмережі',
  thisLoginAlreadyTaken: 'Цей логін вже зайнятий!',
  fieldIsRequired: `Поле обов'язкове!`,
  fields_to_complete_registration:
    'Заповніть всі поля, щоб продовжити реєстрацію',
  confirmation_code: 'Код підтвердження',
  enter_the_code_that_came_to_your_mail:
    'Введіть код, який надійшов вам на пошту',
  resend_code: 'Надіслати код повторно',
  resend_code_via: 'Повторно надіслати код через',
  seconds: 'секунд',
  minimum_six_characters: 'Мінімум 6 символів!',
  newActivities: 'Нова активність',
  title: 'Заголовок',
  description: 'Опис',
  categories: 'Категорії',
  add: 'Добавити',
  who_would_you_like: 'З ким ви хотіли б виконати дію?',
  a_man: 'Чоловіком',
  a_women: 'Жінкою',
  by_the_company: 'Компанією',
  all_the_same: 'Все одно',
  unfollow: 'Відписатись',
  follow: 'Стежити',
  following: 'Відстежується',
  select_categories: 'Виберіть категорії',
  category_search: 'Пошук категорії',
  add_categories_maximum: 'Додати категорії, максимально 3',
  edit_profile: 'Редагувати профіль',
  followers: 'Читачі',
  publications: 'Публікації',
  followings: 'Відстежуються',
  save: 'Зберегти',
  age: 'Вік',
};
