export const activitiesConstants = {
  GET_ACTIVITIES: 'GET_ACTIVITIES',
  GET_ACTIVITIES_SUCCESS: 'GET_ACTIVITIES_SUCCESS',
  GET_MY_ACTIVITIES_SUCCESS: 'GET_MY_ACTIVITIES_SUCCESS',
  GET_ACTIVITIES_FAILURE: 'GET_ACTIVITIES_FAILURE',

  GET_ACTIVITIES_CATEGORIES: 'GET_ACTIVITIES_CATEGORIES',
  GET_ACTIVITIES_CATEGORIES_SUCCESS: 'GET_ACTIVITIES_CATEGORIES_SUCCESS',
  GET_ACTIVITIES_CATEGORIES_FAILURE: 'GET_ACTIVITIES_CATEGORIES_FAILURE',

  CREATE_NEW_ACTIVITIES: 'CREATE_NEW_ACTIVITIES',
  CREATE_NEW_ACTIVITIES_SUCCESS: 'CREATE_NEW_ACTIVITIES_SUCCESS',
  CREATE_NEW_ACTIVITIES_FAILURE: 'CREATE_NEW_ACTIVITIES_FAILURE',
  CREATE_NEW_ACTIVITIES_ERROR: 'CREATE_NEW_ACTIVITIES_ERROR',
};
