export const activitiesConstants = {
  GET_ACTIVITIES: 'GET_ACTIVITIES',
  GET_ACTIVITIES_SUCCESS: 'GET_ACTIVITIES_SUCCESS',
  GET_ACTIVITIES_FAILURE: 'GET_ACTIVITIES_FAILURE',

  GET_SUBSCRIPTIONS_ACTIVITIES: 'GET_SUBSCRIPTIONS_ACTIVITIES',
  GET_SUBSCRIPTIONS_ACTIVITIES_SUCCESS: 'GET_SUBSCRIPTIONS_ACTIVITIES_SUCCESS',
  GET_SUBSCRIPTIONS_ACTIVITIES_FAILURE: 'GET_SUBSCRIPTIONS_ACTIVITIES_FAILURE',

  GET_MY_ACTIVITIES: 'GET_MY_ACTIVITIES',
  GET_MY_ACTIVITIES_SUCCESS: 'GET_MY_ACTIVITIES_SUCCESS',
  GET_MY_ACTIVITIES_FAILURE: 'GET_MY_ACTIVITIES_FAILURE',

  GET_ACTIVITIES_CATEGORIES: 'GET_ACTIVITIES_CATEGORIES',
  GET_ACTIVITIES_CATEGORIES_SUCCESS: 'GET_ACTIVITIES_CATEGORIES_SUCCESS',
  GET_ACTIVITIES_CATEGORIES_FAILURE: 'GET_ACTIVITIES_CATEGORIES_FAILURE',

  CREATE_NEW_ACTIVITIES: 'CREATE_NEW_ACTIVITIES',
  CREATE_NEW_ACTIVITIES_SUCCESS: 'CREATE_NEW_ACTIVITIES_SUCCESS',
  CREATE_NEW_ACTIVITIES_FAILURE: 'CREATE_NEW_ACTIVITIES_FAILURE',
  CREATE_NEW_ACTIVITIES_ERROR: 'CREATE_NEW_ACTIVITIES_ERROR',

  SUBSCRIBE_ACTIVITY: 'SUBSCRIBE_ACTIVITY',
  SUBSCRIBE_ACTIVITY_SUCCESS: 'SUBSCRIBE_ACTIVITY_SUCCESS',
  SUBSCRIBE_ACTIVITY_FAILURE: 'SUBSCRIBE_ACTIVITY_FAILURE',

  UNSUBSCRIBE_ACTIVITY: 'UNSUBSCRIBE_ACTIVITY',
  UNSUBSCRIBE_ACTIVITY_SUCCESS: 'UNSUBSCRIBE_ACTIVITY_SUCCESS',
  UNSUBSCRIBE_ACTIVITY_FAILURE: 'UNSUBSCRIBE_ACTIVITY_FAILURE',
};
