export const images = {
  startBackground: require('./start.png'),
  signInBackground: require('./SignInBackground.png'),
  mamahood: require('./mamahood.png'),
  imgInfo1: require('./mama-info-1.png'),
  imgInfo2: require('./mama-info-2.png'),
  imgInfo3: require('./mama-info-3.png'),

  boyBlack: require('./gender/boy-black.png'),
  boyWhite: require('./gender/boy-white.png'),
  girlWhite: require('./gender/girl-white.png'),
  girlBlack: require('./gender/girl-black.png'),
  boyTerquoise: require('./gender/boyTerquoise.png'),
  girlPink: require('./gender/girlPink.png'),
  girls: require('./girls.png'),
  stethoscope: require('./stethoscope.png'),
  heart: require('./heart.png'),

  logo: require('./logo.png'),
  usa: require('./flags/usa.png'),
  ua: require('./flags/ua.png'),
  ru: require('./flags/ru.png'),

  haveChildren: require('./have-children.png'),
  removeCircle: require('./circle-remove.png'),

  selectPhoto: require('./selectPhoto.png'),

  // baby
  baby1: require('./baby/baby-1.png'),
  baby2: require('./baby/baby-2.png'),
  baby3: require('./baby/baby-3.png'),
  baby4: require('./baby/baby-4.png'),
  baby5: require('./baby/baby-5.png'),
  baby6: require('./baby/baby-6.png'),
  baby7: require('./baby/baby-7.png'),
  baby8: require('./baby/baby-8.png'),
  baby9: require('./baby/baby-9.png'),
  baby10: require('./baby/baby-10.png'),
  baby11: require('./baby/baby-11.png'),
  baby12: require('./baby/baby-12.png'),
  baby13: require('./baby/baby-13.png'),
  baby14: require('./baby/baby-14.png'),
  baby15: require('./baby/baby-15.png'),
  baby16: require('./baby/baby-16.png'),
  baby17: require('./baby/baby-17.png'),

  addPregnancy: require('./add_pregnancy.png'),

  verifyTime: require('./verify-time.png'),
  moodBoy: require('./mood-boy.png'),
  rainDrop: require('./rain-drop.png'),
  atom: require('./atom.png'),
  calendarHeader: require('./calendar-header.png'),
  bell: require('./bell.png'),
  // Footer
  calendarSelected: require('./footer/calendar-selected.png'),
  calendar: require('./footer/calendar.png'),
  forum: require('./footer/forum.png'),
  forumSelected: require('./footer/forum-selected.png'),
  messengerSelected: require('./footer/mesenger-selected.png'),
  messenger: require('./footer/mesenger.png'),
  menuSelected: require('./footer/menu-selected.png'),
  menu: require('./footer/menu.png'),
  calendarPhoto: require('./photo.png'),
  calendarBook: require('./book.png'),

  // MENU

  helpMenu: require('./menu/help.png'),
  leafMenu: require('./menu/leaf.png'),
  timerMenu: require('./menu/timer.png'),
  logoutMenu: require('./menu/logout.png'),
  notificationMenu: require('./menu/notification.png'),
  settingsMenu: require('./menu/settings.png'),
  arrowMenu: require('./menu/arrow.png'),
  defaultUser: require('./default-user.png'),
  girlBtnB: require('./genderBtn/girlB.png'),
  girlBtnW: require('./genderBtn/girlW.png'),

  boyBtnW: require('./genderBtn/boyW.png'),
  boyBtnB: require('./genderBtn/boyB.png'),
  pencil: require('./pencil.png'),
  chats: require('./chats.png'),

  // Profile
  forumPlaceholder: require('./forum-placeholder.png'),
  removePhoto: require('./remove_photo.png'),
  age: require('./profile/age.png'),
  beauty: require('./profile/beauty.png'),
  cooking: require('./profile/cooking.png'),
  interests: require('./profile/interests.png'),
  lang: require('./profile/lang.png'),
  mat_status: require('./profile/mat_status.png'),
  nationality: require('./profile/nationality.png'),
  sport: require('./profile/sport.png'),
  yoga: require('./profile/yoga.png'),
  send: require('./send.png'),
  plus: require('./plus.png'),
  dropdown: require('./dropdown.png'),
  photoDevice: require('./photoDevice.png'),
  chevronRight: require('./chevron-right.png'),
  plusInt: require('./plus_int.png'),
  diamond: require('./diamond.png'),
  noGrowth: require('./no_growth.png')
};
