export const ru = {
  singIn: 'Вход',
  signUp: 'Регистрация',
  publish: 'Публиковать',
  forgotPassword: 'Забыли пароль?',
  continue: 'Продолжить',
  password: 'Пароль',
  edit: 'Редактировать',
  actual: 'Актуальные',
  my: 'Мои',
  filters: 'Фильтры',
  tagline: 'Мы не строим границ между людьми, мы объединяем их.',
  enter_your_email:
    'Введите вашу электронную почту на которое должно прийти письмо с кодом подтверждения',
  password_mismatch: 'Пароли не совпадают!',
  repeat_password: 'Повторите пароль',
  login: 'Логин',
  fields_to_complete_registration:
    'Заполните все поля чтобы завершить регистрацию',
  confirmation_code: 'Код подтверждения',
  enter_the_code_that_came_to_your_mail:
    'Введите код, который пришел вам на почту',
  resend_code: 'Отправить код еще раз',
  resend_code_via: 'Повторно отправить код через',
  seconds: 'секунды',
  minimum_six_characters: 'Минимум 6 символов!',
  newActivities: 'Новая активность',
  title: 'Заголовок',
  description: 'Описание',
  categories: 'Категории',
  add: 'Добавить',
  who_would_you_like: 'С кем бы вы хотели выполнить действие?',
  a_man: 'Мужчиной',
  a_women: 'Женщиной',
  by_the_company: 'Компанией',
  all_the_same: 'Все ровно',
  select_categories: 'Выберете категории',
  category_search: 'Поиск категории',
  add_categories_maximum: 'Добавьте категории, максимально 3',
};
