export const ua = {
  singIn: 'Вхід',
  signUp: 'Реєстрація',
  publish: 'Опублікувати',
  forgotPassword: 'Забули пароль?',
  continue: 'Продовжити',
  password: 'Пароль',
  tagline: "Ми не будуємо кордонів між людьми, ми об'єднуємо їх.",
  edit: 'Редагувати',
  actual: 'Актуальні',
  last_name: 'Фамілія',
  first_name: 'Ім`я',
  filters: 'Фільтри',
  settings: 'Налаштування',
  change_password: 'Змінити пароль',
  logout: 'Вийти',
  language: 'Мова',
  my: 'Мої',
  enter_your_email:
    'Введіть вашу електронну пошту, на який має прийти лист із кодом підтвердження',
  password_mismatch: 'Паролі не співпадають!',
  repeat_password: 'Повторіть пароль',
  login: 'Логін',
  fields_to_complete_registration:
    'Заповніть всі поля, щоб завершити реєстрацію',
  confirmation_code: 'Код підтвердження',
  enter_the_code_that_came_to_your_mail:
    'Введіть код, який надійшов вам на пошту',
  resend_code: 'Надіслати код повторно',
  resend_code_via: 'Повторно надіслати код через',
  seconds: 'секунд',
  minimum_six_characters: 'Мінімум 6 символів!',
  newActivities: 'Нова активність',
  title: 'Заголовок',
  description: 'Опис',
  categories: 'Категорії',
  add: 'Добавити',
  who_would_you_like: 'З ким ви хотіли б виконати дію?',
  a_man: 'Чоловіком',
  a_women: 'Жінкою',
  by_the_company: 'Компанією',
  all_the_same: 'Все одно',
  select_categories: 'Виберіть категорії',
  category_search: 'Пошук категорії',
  add_categories_maximum: 'Додати категорії, максимально 3',
  edit_profile: 'Редагувати профіль',
  save: 'Зберегти',
  age: 'Вік',
};
