export const authConstants = {
  CREATE_AUTH_REQUEST: 'CREATE_AUTH_REQUEST',
  CREATE_AUTH_SUCCESS: 'CREATE_AUTH_SUCCESS',
  CREATE_AUTH_FAILURE: 'CREATE_AUTH_FAILURE',

  SIGN_UP_REQUEST: 'SIGN_UP_REQUEST',
  SIGN_UP_SUCCESS: 'SIGN_UP_SUCCESS',
  SIGN_UP_FAILURE: 'SIGN_UP_FAILURE',

  REFRESH_TOKEN_REQUEST: 'REFRESH_TOKEN_REQUEST',
  REFRESH_TOKEN_SUCCESS: 'REFRESH_TOKEN_SUCCESS',
  REFRESH_TOKEN_FAILURE: 'REFRESH_TOKEN_FAILURE',

  VERIFICATION_EMAIL_REQUEST: 'VERIFICATION_EMAIL_REQUEST',
  VERIFICATION_EMAIL_SUCCESS: 'VERIFICATION_EMAIL_SUCCESS',
  VERIFICATION_EMAIL_FAILURE: 'VERIFICATION_EMAIL_FAILURE',

  FORGOT_PASSWORD_REQUEST: 'FORGOT_PASSWORD_REQUEST',
  FORGOT_PASSWORD_SUCCESS: 'RESET_PASSWORD_SUCCESS',
  FORGOT_PASSWORD_FAILURE: 'RESET_PASSWORD_FAILURE',

  VERIFICATION_FORGOT_PASSWORD_REQUEST: 'VERIFICATION_FORGOT_PASSWORD_REQUEST',
  VERIFICATION_FORGOT_PASSWORD_SUCCESS: 'VERIFICATION_FORGOT_PASSWORD_SUCCESS',
  VERIFICATION_FORGOT_PASSWORD_FAILURE: 'VERIFICATION_FORGOT_PASSWORD_FAILURE',

  RESEND_CODE_REQUEST: 'RESEND_CODE_REQUEST',
  RESEND_CODE_SUCCESS: 'RESEND_CODE_SUCCESS',
  RESEND_CODE_FAILURE: 'RESEND_CODE_FAILURE',

  RESET_PASSWORD_REQUEST: 'RESET_PASSWORD_REQUEST',
  RESET_PASSWORD_SUCCESS: 'RESET_PASSWORD_SUCCESS',
  RESET_PASSWORD_FAILURE: 'RESET_PASSWORD_FAILURE',

  CONTINUE_REGISTER_REQUEST: 'CONTINUE_REGISTER_REQUEST',
  CONTINUE_REGISTER_SUCCESS: 'CONTINUE_REGISTER_SUCCESS',
  CONTINUE_REGISTER_FAILURE: 'CONTINUE_REGISTER_FAILURE',

  SET_ERROR_LOGIN: 'SET_ERROR_LOGIN',
  SET_ERROR_REGISTER: 'SET_ERROR_REGISTER',
  SET_ERROR_REGISTER_CODE_VERIFY: 'SET_ERROR_REGISTER_CODE_VERIFY',
  SET_ERROR_CONTINUE_REGISTER: 'SET_ERROR_CONTINUE_REGISTER',
  SET_ERROR_FORGOT_PASSWORD: 'SET_ERROR_FORGOT_PASSWORD',
  SET_ERROR_VERIFICATION_FORGOT_PASSWORD:
    'SET_ERROR_VERIFICATION_FORGOT_PASSWORD',
  SET_ERROR_PASSWORD_RESET: 'SET_ERROR_PASSWORD_RESET',

  SET_TOKEN_REQUEST: 'SET_TOKEN_REQUEST',
  SET_TOKEN_SUCCESS: 'SET_TOKEN_SUCCESS',

  REMOVE_TOKEN_SUCCESS: 'REMOVE_TOKEN_SUCCESS',
};
